openapi: "3.0.3"

info:
  title: "Iced Latte Payment API"
  description: "API for accessing payment and related operations in the Iced-Latte platform"
  version: "1.0.0"
  contact:
    name: "Iced Latte Support"
    email: "zufar.sunagatov@gmail.com"

servers:
  - url: "http://localhost:8083"
    description: "Local development server"
  - url: "https://il.pride.improwised.local/backend"
    description: "Production server"

tags:
  - name: "Payment"
    description: "An API for managing and retrieving payment information"

paths:
  /api/v1/payment:
    post:
      tags:
        - "Payment"
      summary: "Creates Stripe Session for an authorized user"
      operationId: "processPayment"
      responses:
        "200":
          description: "Session created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionWithClientSecretDto"
        "400":
          description: "Cannot create session"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorHandler"

components:
  schemas:
    PaymentStatus:
      type: "object"
      properties:
        status:
          type: "string"
        description:
          type: "string"

    SessionWithClientSecretDto:
      type: "object"
      properties:
        sessionId:
          type: "string"
        clientSecret:
          type: "string"

    ErrorHandler:
      type: "object"
      properties:
        messages:
          type: "array"
          items:
            format: "string"
        description:
          type: "string"
        httpStatusCode:
          type: "integer"
          format: "int32"
        timestamp:
          type: "string"
          format: "date-time"
