openapi: "3.0.3"

info:
  title: "Iced Latte Security API"
  description: "API for accessing security and related operations in the Iced-Latte platform"
  version: "1.0.0"
  contact:
    name: "Iced Latte Support"
    email: "zufar.sunagatov@gmail.com"

servers:
  - url: "http://localhost:8083"
    description: "Local development server"
  - url: "https://il.pride.improwised.local/backend"
    description: "Production server"

tags:
  - name: "Security"
    description: "An API for user registration and authentication"

paths:
  /api/v1/auth/register:
    post:
      tags:
        - "Security"
      summary: "Register a user"
      operationId: "register"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: string

  /api/v1/auth/confirm:
    post:
      tags:
        - "Security"
      summary: "Confirm an email"
      operationId: "confirmEmail"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConfirmEmailRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRegistrationResponse"

  /api/v1/auth/authenticate:
    post:
      tags:
        - "Security"
      summary: "Authenticate a user"
      operationId: "authenticate"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthenticationRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAuthenticationResponse"

  /api/v1/auth/logout:
    post:
      tags:
        - "Security"
      summary: "Logout user"
      operationId: "logout"
      responses:
        "200":
          description: "OK"
        "500":
          description: "Internal Server Error"

  /api/v1/auth/refresh:
    post:
      tags:
        - "Security"
      summary: "Refresh user token"
      operationId: "refreshToken"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAuthenticationResponse"
        "401":
          description: "Unauthorized access. Authentication required"
        "500":
          description: "Internal Server Error"

  /api/v1/auth/password/forgot:
    post:
      tags:
        - "Security"
      summary: "Send email with verification code"
      operationId: "forgotPassword"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgotPasswordRequest"
        required: true
      responses:
        "200":
          description: "OK"
        "401":
          description: "Unauthorized access. Authentication required"
        "500":
          description: "Internal Server Error"

  /api/v1/auth/password/change:
    post:
      tags:
        - "Security"
      summary: "Change password with verification code"
      operationId: "changePassword"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangePasswordRequest"
        required: true
      responses:
        "200":
          description: "OK"
        "401":
          description: "Unauthorized access. Authentication required"
        "500":
          description: "Internal Server Error"
  /api/v1/auth/email/code:
    post:
      tags:
        - "Security"
      summary: "Get email code"
      operationId: "getEmailVerificationCode"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    UserRegistrationRequest:
      type: "object"
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"

    UserRegistrationResponse:
      type: "object"
      properties:
        token:
          type: "string"
        refreshToken:
          type: "string"

    UserAuthenticationRequest:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"

    ConfirmEmailRequest:
      type: "object"
      properties:
        token:
          type: "string"

    UserAuthenticationResponse:
      type: "object"
      properties:
        token:
          type: "string"
        refreshToken:
          type: "string"

    ForgotPasswordRequest:
      type: "object"
      properties:
        email:
          type: "string"

    ChangePasswordRequest:
      type: "object"
      properties:
        email:
          type: "string"
        code:
          type: "string"
        password:
          type: "string"
